[
  { "name": "Afghanistan", "currencyCode": "AFN", "currencySymbol": "؋" },
  { "name": "Albania", "currencyCode": "ALL", "currencySymbol": "L" },
  { "name": "Algeria", "currencyCode": "DZD", "currencySymbol": "دج" },
  { "name": "Andorra", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Angola", "currencyCode": "AOA", "currencySymbol": "Kz" },
  { "name": "Argentina", "currencyCode": "ARS", "currencySymbol": "$" },
  { "name": "Armenia", "currencyCode": "AMD", "currencySymbol": "֏" },
  { "name": "Australia", "currencyCode": "AUD", "currencySymbol": "A$" },
  { "name": "Austria", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Azerbaijan", "currencyCode": "AZN", "currencySymbol": "₼" },
  { "name": "Bahamas", "currencyCode": "BSD", "currencySymbol": "B$" },
  { "name": "Bahrain", "currencyCode": "BHD", "currencySymbol": ".د.ب" },
  { "name": "Bangladesh", "currencyCode": "BDT", "currencySymbol": "৳" },
  { "name": "Barbados", "currencyCode": "BBD", "currencySymbol": "Bds$" },
  { "name": "Belarus", "currencyCode": "BYN", "currencySymbol": "Br" },
  { "name": "Belgium", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Belize", "currencyCode": "BZD", "currencySymbol": "BZ$" },
  { "name": "Benin", "currencyCode": "XOF", "currencySymbol": "CFA" },
  { "name": "Bhutan", "currencyCode": "BTN", "currencySymbol": "Nu." },
  { "name": "Bolivia", "currencyCode": "BOB", "currencySymbol": "Bs." },
  {
    "name": "Bosnia and Herzegovina",
    "currencyCode": "BAM",
    "currencySymbol": "KM"
  },
  { "name": "Botswana", "currencyCode": "BWP", "currencySymbol": "P" },
  { "name": "Brazil", "currencyCode": "BRL", "currencySymbol": "R$" },
  { "name": "Brunei", "currencyCode": "BND", "currencySymbol": "B$" },
  { "name": "Bulgaria", "currencyCode": "BGN", "currencySymbol": "лв" },
  { "name": "Burkina Faso", "currencyCode": "XOF", "currencySymbol": "CFA" },
  { "name": "Burundi", "currencyCode": "BIF", "currencySymbol": "FBu" },
  { "name": "Cambodia", "currencyCode": "KHR", "currencySymbol": "៛" },
  { "name": "Cameroon", "currencyCode": "XAF", "currencySymbol": "FCFA" },
  { "name": "Canada", "currencyCode": "CAD", "currencySymbol": "C$" },
  { "name": "Cape Verde", "currencyCode": "CVE", "currencySymbol": "Esc" },
  {
    "name": "Central African Republic",
    "currencyCode": "XAF",
    "currencySymbol": "FCFA"
  },
  { "name": "Chad", "currencyCode": "XAF", "currencySymbol": "FCFA" },
  { "name": "Chile", "currencyCode": "CLP", "currencySymbol": "$" },
  { "name": "China", "currencyCode": "CNY", "currencySymbol": "¥" },
  { "name": "Colombia", "currencyCode": "COP", "currencySymbol": "$" },
  { "name": "Comoros", "currencyCode": "KMF", "currencySymbol": "CF" },
  { "name": "Congo", "currencyCode": "XAF", "currencySymbol": "FCFA" },
  { "name": "Costa Rica", "currencyCode": "CRC", "currencySymbol": "₡" },
  { "name": "Croatia", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Cuba", "currencyCode": "CUP", "currencySymbol": "₱" },
  { "name": "Cyprus", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Czech Republic", "currencyCode": "CZK", "currencySymbol": "Kč" },
  { "name": "Denmark", "currencyCode": "DKK", "currencySymbol": "kr" },
  { "name": "Djibouti", "currencyCode": "DJF", "currencySymbol": "Fdj" },
  {
    "name": "Dominican Republic",
    "currencyCode": "DOP",
    "currencySymbol": "RD$"
  },
  { "name": "Ecuador", "currencyCode": "USD", "currencySymbol": "$" },
  { "name": "Egypt", "currencyCode": "EGP", "currencySymbol": "£" },
  { "name": "El Salvador", "currencyCode": "USD", "currencySymbol": "$" },
  { "name": "Estonia", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Eswatini", "currencyCode": "SZL", "currencySymbol": "E" },
  { "name": "Ethiopia", "currencyCode": "ETB", "currencySymbol": "Br" },
  { "name": "Fiji", "currencyCode": "FJD", "currencySymbol": "FJ$" },
  { "name": "Finland", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "France", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Gabon", "currencyCode": "XAF", "currencySymbol": "FCFA" },
  { "name": "Gambia", "currencyCode": "GMD", "currencySymbol": "D" },
  { "name": "Georgia", "currencyCode": "GEL", "currencySymbol": "₾" },
  { "name": "Germany", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Ghana", "currencyCode": "GHS", "currencySymbol": "₵" },
  { "name": "Greece", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Guatemala", "currencyCode": "GTQ", "currencySymbol": "Q" },
  { "name": "Honduras", "currencyCode": "HNL", "currencySymbol": "L" },
  { "name": "Hungary", "currencyCode": "HUF", "currencySymbol": "Ft" },
  { "name": "Iceland", "currencyCode": "ISK", "currencySymbol": "kr" },
  { "name": "India", "currencyCode": "INR", "currencySymbol": "₹" },
  { "name": "Indonesia", "currencyCode": "IDR", "currencySymbol": "Rp" },
  { "name": "Iran", "currencyCode": "IRR", "currencySymbol": "﷼" },
  { "name": "Iraq", "currencyCode": "IQD", "currencySymbol": "ع.د" },
  { "name": "Ireland", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Israel", "currencyCode": "ILS", "currencySymbol": "₪" },
  { "name": "Italy", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Iceland", "currencyCode": "ISK", "currencySymbol": "kr" },
  { "name": "India", "currencyCode": "INR", "currencySymbol": "₹" },
  { "name": "Indonesia", "currencyCode": "IDR", "currencySymbol": "Rp" },
  { "name": "Iran", "currencyCode": "IRR", "currencySymbol": "﷼" },
  { "name": "Iraq", "currencyCode": "IQD", "currencySymbol": "ع.د" },
  { "name": "Ireland", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Israel", "currencyCode": "ILS", "currencySymbol": "₪" },
  { "name": "Italy", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Jamaica", "currencyCode": "JMD", "currencySymbol": "J$" },
  { "name": "Japan", "currencyCode": "JPY", "currencySymbol": "¥" },
  { "name": "Jordan", "currencyCode": "JOD", "currencySymbol": "د.ا" },
  { "name": "Kazakhstan", "currencyCode": "KZT", "currencySymbol": "₸" },
  { "name": "Kenya", "currencyCode": "KES", "currencySymbol": "KSh" },
  { "name": "Kiribati", "currencyCode": "AUD", "currencySymbol": "A$" },
  { "name": "Kuwait", "currencyCode": "KWD", "currencySymbol": "د.ك" },
  { "name": "Kyrgyzstan", "currencyCode": "KGS", "currencySymbol": "лв" },
  { "name": "Laos", "currencyCode": "LAK", "currencySymbol": "₭" },
  { "name": "Latvia", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Lebanon", "currencyCode": "LBP", "currencySymbol": "ل.ل" },
  { "name": "Lesotho", "currencyCode": "LSL", "currencySymbol": "L" },
  { "name": "Liberia", "currencyCode": "LRD", "currencySymbol": "L$" },
  { "name": "Libya", "currencyCode": "LYD", "currencySymbol": "ل.د" },
  { "name": "Liechtenstein", "currencyCode": "CHF", "currencySymbol": "CHF" },
  { "name": "Lithuania", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Luxembourg", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Madagascar", "currencyCode": "MGA", "currencySymbol": "Ar" },
  { "name": "Malawi", "currencyCode": "MWK", "currencySymbol": "MK" },
  { "name": "Malaysia", "currencyCode": "MYR", "currencySymbol": "RM" },
  { "name": "Maldives", "currencyCode": "MVR", "currencySymbol": "Rf" },
  { "name": "Mali", "currencyCode": "XOF", "currencySymbol": "CFA" },
  { "name": "Malta", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Mexico", "currencyCode": "MXN", "currencySymbol": "$" },
  { "name": "Moldova", "currencyCode": "MDL", "currencySymbol": "L" },
  { "name": "Monaco", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Mongolia", "currencyCode": "MNT", "currencySymbol": "₮" },
  { "name": "Montenegro", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Morocco", "currencyCode": "MAD", "currencySymbol": "د.م." },
  { "name": "Mozambique", "currencyCode": "MZN", "currencySymbol": "MT" },
  { "name": "Myanmar", "currencyCode": "MMK", "currencySymbol": "K" },
  { "name": "Namibia", "currencyCode": "NAD", "currencySymbol": "N$" },
  { "name": "Nauru", "currencyCode": "AUD", "currencySymbol": "A$" },
  { "name": "Nepal", "currencyCode": "NPR", "currencySymbol": "रू" },
  { "name": "Netherlands", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "New Zealand", "currencyCode": "NZD", "currencySymbol": "NZ$" },
  { "name": "Nicaragua", "currencyCode": "NIO", "currencySymbol": "C$" },
  { "name": "Niger", "currencyCode": "XOF", "currencySymbol": "CFA" },
  { "name": "Nigeria", "currencyCode": "NGN", "currencySymbol": "₦" },
  { "name": "North Macedonia", "currencyCode": "MKD", "currencySymbol": "ден" },
  { "name": "Norway", "currencyCode": "NOK", "currencySymbol": "kr" },
  { "name": "Oman", "currencyCode": "OMR", "currencySymbol": "ر.ع." },
  { "name": "Pakistan", "currencyCode": "PKR", "currencySymbol": "₨" },
  { "name": "Palau", "currencyCode": "USD", "currencySymbol": "$" },
  { "name": "Panama", "currencyCode": "PAB", "currencySymbol": "B/." },
  {
    "name": "Papua New Guinea",
    "currencyCode": "PGK",
    "currencySymbol": "K"
  },
  { "name": "Paraguay", "currencyCode": "PYG", "currencySymbol": "₲" },
  { "name": "Peru", "currencyCode": "PEN", "currencySymbol": "S/." },
  { "name": "Philippines", "currencyCode": "PHP", "currencySymbol": "₱" },
  { "name": "Poland", "currencyCode": "PLN", "currencySymbol": "zł" },
  { "name": "Portugal", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Qatar", "currencyCode": "QAR", "currencySymbol": "ر.ق" },
  { "name": "Romania", "currencyCode": "RON", "currencySymbol": "lei" },
  { "name": "Russia", "currencyCode": "RUB", "currencySymbol": "₽" },
  { "name": "Rwanda", "currencyCode": "RWF", "currencySymbol": "FRw" },
  {
    "name": "Saint Kitts and Nevis",
    "currencyCode": "XCD",
    "currencySymbol": "EC$"
  },
  { "name": "Saint Lucia", "currencyCode": "XCD", "currencySymbol": "EC$" },
  {
    "name": "Saint Vincent and the Grenadines",
    "currencyCode": "XCD",
    "currencySymbol": "EC$"
  },
  { "name": "Samoa", "currencyCode": "WST", "currencySymbol": "T" },
  { "name": "San Marino", "currencyCode": "EUR", "currencySymbol": "€" },
  {
    "name": "Sao Tome and Principe",
    "currencyCode": "STN",
    "currencySymbol": "Db"
  },
  { "name": "Saudi Arabia", "currencyCode": "SAR", "currencySymbol": "ر.س" },
  { "name": "Senegal", "currencyCode": "XOF", "currencySymbol": "CFA" },
  { "name": "Serbia", "currencyCode": "RSD", "currencySymbol": "дин." },
  { "name": "Seychelles", "currencyCode": "SCR", "currencySymbol": "₨" },
  { "name": "Sierra Leone", "currencyCode": "SLL", "currencySymbol": "Le" },
  { "name": "Singapore", "currencyCode": "SGD", "currencySymbol": "$" },
  { "name": "Slovakia", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Slovenia", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Solomon Islands", "currencyCode": "SBD", "currencySymbol": "$" },
  { "name": "Somalia", "currencyCode": "SOS", "currencySymbol": "Sh" },
  { "name": "South Africa", "currencyCode": "ZAR", "currencySymbol": "R" },
  { "name": "South Sudan", "currencyCode": "SSP", "currencySymbol": "£" },
  { "name": "Spain", "currencyCode": "EUR", "currencySymbol": "€" },
  { "name": "Sri Lanka", "currencyCode": "LKR", "currencySymbol": "Rs" },
  { "name": "Sudan", "currencyCode": "SDG", "currencySymbol": "ج.س." },
  { "name": "Suriname", "currencyCode": "SRD", "currencySymbol": "$" },
  { "name": "Sweden", "currencyCode": "SEK", "currencySymbol": "kr" },
  { "name": "Switzerland", "currencyCode": "CHF", "currencySymbol": "CHF" },
  { "name": "Syria", "currencyCode": "SYP", "currencySymbol": "£" },
  { "name": "Taiwan", "currencyCode": "TWD", "currencySymbol": "NT$" },
  { "name": "Tajikistan", "currencyCode": "TJS", "currencySymbol": "SM" },
  { "name": "Tanzania", "currencyCode": "TZS", "currencySymbol": "Sh" },
  { "name": "Thailand", "currencyCode": "THB", "currencySymbol": "฿" },
  { "name": "Timor-Leste", "currencyCode": "USD", "currencySymbol": "$" },
  { "name": "Togo", "currencyCode": "XOF", "currencySymbol": "CFA" },
  { "name": "Tonga", "currencyCode": "TOP", "currencySymbol": "T$" },
  {
    "name": "Trinidad and Tobago",
    "currencyCode": "TTD",
    "currencySymbol": "$"
  },
  { "name": "Tunisia", "currencyCode": "TND", "currencySymbol": "د.ت" },
  { "name": "Turkey", "currencyCode": "TRY", "currencySymbol": "₺" },
  { "name": "Turkmenistan", "currencyCode": "TMT", "currencySymbol": "m" },
  { "name": "Tuvalu", "currencyCode": "AUD", "currencySymbol": "A$" },
   { "name": "Uganda", "currencyCode": "UGX", "currencySymbol": "Sh" },
   { "name": "Ukraine", "currencyCode": "UAH", "currencySymbol": "₴" },
   {
     "name": "United Arab Emirates",
     "currencyCode": "AED",
     "currencySymbol": "د.إ"
   },
   { "name": "United Kingdom", "currencyCode": "GBP", "currencySymbol": "£" },
   { "name": "United States", "currencyCode": "USD", "currencySymbol": "$" },
   { "name": "Uruguay", "currencyCode": "UYU", "currencySymbol": "$U" },
   { "name": "Uzbekistan", "currencyCode": "UZS", "currencySymbol": "so'm" },
   { "name": "Vanuatu", "currencyCode": "VUV", "currencySymbol": "Vt" },
   { "name": "Vatican City", "currencyCode": "EUR", "currencySymbol": "€" },
   { "name": "Venezuela", "currencyCode": "VES", "currencySymbol": "Bs." },
   { "name": "Vietnam", "currencyCode": "VND", "currencySymbol": "₫" },
   { "name": "Yemen", "currencyCode": "YER", "currencySymbol": "﷼" },
   { "name": "Zambia", "currencyCode": "ZMW", "currencySymbol": "ZK" },
   { "name": "Zimbabwe", "currencyCode": "ZWL", "currencySymbol": "$" }
 ]
